version: "3"

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo17
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./odoo17-db-data:/var/lib/postgresql/data

  odoo_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=postgress
      - DB_PORT=5432
      - DB_USER=odoo17
      - DB_PASSWORD=odoo
    volumes:
      - ./customs:/customs
      - ./etc/odoo:/etc/odoo
      - odoo17-web-data:/var/lib/odoo

volumes:
  odoo17-web-data:
  odoo17-postgress-data:
